### ISSUE TITLE
Remote ABI Agents -  Use Secrets from Assistant

### ISSUE THREAD

**Issue by FlorentLvr** [jupyter-naas/abi#309]
The objective is to be able to use user config in specific assistant if the config exists.

Back-end:
- Create Connections API to be able to set keys/credentials directly from front
- Update Agent config to use user connections: for now, tools are set inside the agent with existing connections. We need to be able to set it from outsite. 
- Add Boolean to Trust or Not Agent in the Agent Panel: if a user set a new remote agent and is not admin, we need to make sure this agent won't use your personal connection without the verification of workspace admin.

Front-end:
- Manage connections: JSON to be provided from abi to Front
```
- name: LinkedIn
- logo_url: ...
- description: ....
- fields:
  - name: li_at
    description: xxxx
    type: "str"
    value: "xxxxx"
  - name: JSESSIONID
    description: xxxx
    type: "str"
    value: "xxxxx"
```
- Assistants config:
1. Add fields to set remote URL
2. Add boolean 'Trust' to use personal connections
3. Display connections needed + Be able to select connections from users.connections
- GitHub: Global or User or Nothing with Override or Not
- LinkedIn: Global or User or Nothing with Override or Not
